
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myproject
    username: demo
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  messages:
    basename: static/messages

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: spring-boot-jwt-authentication
  lifetime: 7200  # 2 hours
